/**
 * Action Types
 * @type {string}
 */

// auth action types
export const AUTH_API_LOADING = 'AUTH_API_LOADING'
export const FAILED_AUTH_API = 'FAILED_AUTH_API'
export const CHANGE_LOGIN_STATE = 'CHANGE_LOGIN_STATE'
export const SUCCESS_LOG_IN = 'SUCCESS_LOG_IN'

export const SUCCESS_SIGN_UP = 'SUCCESS_SIGN_UP'

export const SUCCESS_LOG_OUT = 'SUCCESS_LOG_OUT'

// browse action types
export const BROWSE_API_LOADING = 'BROWSE_API_LOADING'
export const FAILED_BROWSE_API = 'FAILED_BROWSE_API'

export const ON_CHANGE_PAGE_NUM = 'ON_CHANGE_PAGE_NUM'

export const ON_CHANGE_PAGE_SIZE = 'ON_CHANGE_PAGE_SIZE'

export const SUCCESS_GET_BROWSE_DATA = 'SUCCESS_GET_BROWSE_DATA'

export const SUCCESS_GET_DATA_FROM_START_AND_END = 'SUCCESS_GET_DATA_FROM_START_AND_END'

export const SUCCESS_GET_ASTEROID_BY_ID = 'SUCCESS_GET_ASTEROID_BY_ID'